#! /usr/bin/env bash
################################################################################
# Generate GRPC stubs for the playcloud project.
################################################################################

readonly FILE_PATH="$(dirname ${BASH_SOURCE[0]})"
readonly DATA_DIRECTORY="$(realpath ${FILE_PATH})"
readonly REPO_DIRECTORY="$(dirname ${DATA_DIRECTORY})"

function print_usage {
  echo -e "usage: $0\n"
  echo -e "Generates GRPC stubs for java-proxy, pyproxy and pycoder from GRPC service deifnition files.\n"
  echo -e "Options:"
  echo -e "\t-h      Print this help message"
}

while getopts ":h" opt; do
  case $opt in
    h)
      print_usage
      exit 0
      ;;
    \?)
      echo "Invalid option: -$OPTARG"
      print_usage
      exit 1
      ;;
  esac
done

if [[ "${#}" -ne 0 ]]; then
	print_usage
	exit 0
fi

protoc -I "${DATA_DIRECTORY}" --python_out="${REPO_DIRECTORY}/pycoder/" --grpc_out="${REPO_DIRECTORY}/pycoder/" --plugin=protoc-gen-grpc="${GRPC_ROOT}"/bins/opt/grpc_python_plugin "${DATA_DIRECTORY}/playcloud.proto"
protoc -I "${DATA_DIRECTORY}" --python_out="${REPO_DIRECTORY}/pyproxy/pyproxy" --grpc_out="${REPO_DIRECTORY}/pyproxy/pyproxy" --plugin=protoc-gen-grpc="${GRPC_ROOT}"/bins/opt/grpc_python_plugin "${DATA_DIRECTORY}/playcloud.proto"
