# Before running this dockerfile please build microbencher.Dockerfile
# e.g: docker build -t pycoder-micro -f microbencher.Dockerfile .

FROM pycoder-micro # microbencher.Dockerfile

ENTRYPOINT /usr/bin/python /usr/local/src/app/server.py