package ch.unine.iiun.safecloud;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: playcloud.proto

public final class Playcloud {
  private Playcloud() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EncodeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EncodeRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes payload = 1;</code>
     */
    com.google.protobuf.ByteString getPayload();

    /**
     * <code>map&lt;string, string&gt; encoding_parameters = 2;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getEncodingParameters();
  }
  /**
   * Protobuf type {@code EncodeRequest}
   */
  public  static final class EncodeRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:EncodeRequest)
      EncodeRequestOrBuilder {
    // Use EncodeRequest.newBuilder() to construct.
    private EncodeRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private EncodeRequest() {
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private EncodeRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              payload_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                encodingParameters_ = com.google.protobuf.MapField.newMapField(
                    EncodingParametersDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              encodingParameters = input.readMessage(
                  EncodingParametersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              encodingParameters_.getMutableMap().put(encodingParameters.getKey(), encodingParameters.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Playcloud.internal_static_EncodeRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetEncodingParameters();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Playcloud.internal_static_EncodeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Playcloud.EncodeRequest.class, Playcloud.EncodeRequest.Builder.class);
    }

    private int bitField0_;
    public static final int PAYLOAD_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>optional bytes payload = 1;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    public static final int ENCODING_PARAMETERS_FIELD_NUMBER = 2;
    private static final class EncodingParametersDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  Playcloud.internal_static_EncodeRequest_EncodingParametersEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> encodingParameters_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetEncodingParameters() {
      if (encodingParameters_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            EncodingParametersDefaultEntryHolder.defaultEntry);
     }
      return encodingParameters_;
    }
    /**
     * <code>map&lt;string, string&gt; encoding_parameters = 2;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getEncodingParameters() {
      return internalGetEncodingParameters().getMap();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!payload_.isEmpty()) {
        output.writeBytes(1, payload_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetEncodingParameters().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        encodingParameters = EncodingParametersDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(2, encodingParameters);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, payload_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetEncodingParameters().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        encodingParameters = EncodingParametersDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, encodingParameters);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static Playcloud.EncodeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Playcloud.EncodeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Playcloud.EncodeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Playcloud.EncodeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Playcloud.EncodeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Playcloud.EncodeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Playcloud.EncodeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Playcloud.EncodeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Playcloud.EncodeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Playcloud.EncodeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Playcloud.EncodeRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EncodeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EncodeRequest)
        Playcloud.EncodeRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Playcloud.internal_static_EncodeRequest_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetEncodingParameters();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableEncodingParameters();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Playcloud.internal_static_EncodeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Playcloud.EncodeRequest.class, Playcloud.EncodeRequest.Builder.class);
      }

      // Construct using ch.unine.iiun.safecloud.Playcloud.EncodeRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        payload_ = com.google.protobuf.ByteString.EMPTY;

        internalGetMutableEncodingParameters().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Playcloud.internal_static_EncodeRequest_descriptor;
      }

      public Playcloud.EncodeRequest getDefaultInstanceForType() {
        return Playcloud.EncodeRequest.getDefaultInstance();
      }

      public Playcloud.EncodeRequest build() {
        Playcloud.EncodeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Playcloud.EncodeRequest buildPartial() {
        Playcloud.EncodeRequest result = new Playcloud.EncodeRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.payload_ = payload_;
        result.encodingParameters_ = internalGetEncodingParameters();
        result.encodingParameters_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Playcloud.EncodeRequest) {
          return mergeFrom((Playcloud.EncodeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Playcloud.EncodeRequest other) {
        if (other == Playcloud.EncodeRequest.getDefaultInstance()) return this;
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        internalGetMutableEncodingParameters().mergeFrom(
            other.internalGetEncodingParameters());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Playcloud.EncodeRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Playcloud.EncodeRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes payload = 1;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>optional bytes payload = 1;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes payload = 1;</code>
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> encodingParameters_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetEncodingParameters() {
        if (encodingParameters_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              EncodingParametersDefaultEntryHolder.defaultEntry);
       }
        return encodingParameters_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableEncodingParameters() {
        onChanged();;
        if (encodingParameters_ == null) {
          encodingParameters_ = com.google.protobuf.MapField.newMapField(
              EncodingParametersDefaultEntryHolder.defaultEntry);
        }
        if (!encodingParameters_.isMutable()) {
          encodingParameters_ = encodingParameters_.copy();
        }
        return encodingParameters_;
      }
      /**
       * <code>map&lt;string, string&gt; encoding_parameters = 2;</code>
       */
      public java.util.Map<java.lang.String, java.lang.String> getEncodingParameters() {
        return internalGetEncodingParameters().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; encoding_parameters = 2;</code>
       */
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableEncodingParameters() {
        return internalGetMutableEncodingParameters().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; encoding_parameters = 2;</code>
       */
      public Builder putAllEncodingParameters(
          java.util.Map<java.lang.String, java.lang.String> values) {
        getMutableEncodingParameters().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:EncodeRequest)
    }

    // @@protoc_insertion_point(class_scope:EncodeRequest)
    private static final Playcloud.EncodeRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Playcloud.EncodeRequest();
    }

    public static Playcloud.EncodeRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EncodeRequest>
        PARSER = new com.google.protobuf.AbstractParser<EncodeRequest>() {
      public EncodeRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new EncodeRequest(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<EncodeRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EncodeRequest> getParserForType() {
      return PARSER;
    }

    public Playcloud.EncodeRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EncodeReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EncodeReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes enc_blocks = 1;</code>
     */
    com.google.protobuf.ByteString getEncBlocks();
  }
  /**
   * Protobuf type {@code EncodeReply}
   */
  public  static final class EncodeReply extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:EncodeReply)
      EncodeReplyOrBuilder {
    // Use EncodeReply.newBuilder() to construct.
    private EncodeReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private EncodeReply() {
      encBlocks_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private EncodeReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              encBlocks_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Playcloud.internal_static_EncodeReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Playcloud.internal_static_EncodeReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Playcloud.EncodeReply.class, Playcloud.EncodeReply.Builder.class);
    }

    public static final int ENC_BLOCKS_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString encBlocks_;
    /**
     * <code>optional bytes enc_blocks = 1;</code>
     */
    public com.google.protobuf.ByteString getEncBlocks() {
      return encBlocks_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!encBlocks_.isEmpty()) {
        output.writeBytes(1, encBlocks_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!encBlocks_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, encBlocks_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static Playcloud.EncodeReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Playcloud.EncodeReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Playcloud.EncodeReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Playcloud.EncodeReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Playcloud.EncodeReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Playcloud.EncodeReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Playcloud.EncodeReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Playcloud.EncodeReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Playcloud.EncodeReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Playcloud.EncodeReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Playcloud.EncodeReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EncodeReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EncodeReply)
        Playcloud.EncodeReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Playcloud.internal_static_EncodeReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Playcloud.internal_static_EncodeReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Playcloud.EncodeReply.class, Playcloud.EncodeReply.Builder.class);
      }

      // Construct using ch.unine.iiun.safecloud.Playcloud.EncodeReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        encBlocks_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Playcloud.internal_static_EncodeReply_descriptor;
      }

      public Playcloud.EncodeReply getDefaultInstanceForType() {
        return Playcloud.EncodeReply.getDefaultInstance();
      }

      public Playcloud.EncodeReply build() {
        Playcloud.EncodeReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Playcloud.EncodeReply buildPartial() {
        Playcloud.EncodeReply result = new Playcloud.EncodeReply(this);
        result.encBlocks_ = encBlocks_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Playcloud.EncodeReply) {
          return mergeFrom((Playcloud.EncodeReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Playcloud.EncodeReply other) {
        if (other == Playcloud.EncodeReply.getDefaultInstance()) return this;
        if (other.getEncBlocks() != com.google.protobuf.ByteString.EMPTY) {
          setEncBlocks(other.getEncBlocks());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Playcloud.EncodeReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Playcloud.EncodeReply) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString encBlocks_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes enc_blocks = 1;</code>
       */
      public com.google.protobuf.ByteString getEncBlocks() {
        return encBlocks_;
      }
      /**
       * <code>optional bytes enc_blocks = 1;</code>
       */
      public Builder setEncBlocks(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        encBlocks_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes enc_blocks = 1;</code>
       */
      public Builder clearEncBlocks() {
        
        encBlocks_ = getDefaultInstance().getEncBlocks();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:EncodeReply)
    }

    // @@protoc_insertion_point(class_scope:EncodeReply)
    private static final Playcloud.EncodeReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Playcloud.EncodeReply();
    }

    public static Playcloud.EncodeReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EncodeReply>
        PARSER = new com.google.protobuf.AbstractParser<EncodeReply>() {
      public EncodeReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new EncodeReply(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<EncodeReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EncodeReply> getParserForType() {
      return PARSER;
    }

    public Playcloud.EncodeReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DecodeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DecodeRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated bytes enc_blocks = 1;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getEncBlocksList();
    /**
     * <code>repeated bytes enc_blocks = 1;</code>
     */
    int getEncBlocksCount();
    /**
     * <code>repeated bytes enc_blocks = 1;</code>
     */
    com.google.protobuf.ByteString getEncBlocks(int index);

    /**
     * <code>map&lt;string, string&gt; decoding_parameters = 2;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getDecodingParameters();
  }
  /**
   * Protobuf type {@code DecodeRequest}
   */
  public  static final class DecodeRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DecodeRequest)
      DecodeRequestOrBuilder {
    // Use DecodeRequest.newBuilder() to construct.
    private DecodeRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DecodeRequest() {
      encBlocks_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private DecodeRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                encBlocks_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              encBlocks_.add(input.readBytes());
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                decodingParameters_ = com.google.protobuf.MapField.newMapField(
                    DecodingParametersDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              decodingParameters = input.readMessage(
                  DecodingParametersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              decodingParameters_.getMutableMap().put(decodingParameters.getKey(), decodingParameters.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          encBlocks_ = java.util.Collections.unmodifiableList(encBlocks_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Playcloud.internal_static_DecodeRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetDecodingParameters();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Playcloud.internal_static_DecodeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Playcloud.DecodeRequest.class, Playcloud.DecodeRequest.Builder.class);
    }

    public static final int ENC_BLOCKS_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> encBlocks_;
    /**
     * <code>repeated bytes enc_blocks = 1;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getEncBlocksList() {
      return encBlocks_;
    }
    /**
     * <code>repeated bytes enc_blocks = 1;</code>
     */
    public int getEncBlocksCount() {
      return encBlocks_.size();
    }
    /**
     * <code>repeated bytes enc_blocks = 1;</code>
     */
    public com.google.protobuf.ByteString getEncBlocks(int index) {
      return encBlocks_.get(index);
    }

    public static final int DECODING_PARAMETERS_FIELD_NUMBER = 2;
    private static final class DecodingParametersDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  Playcloud.internal_static_DecodeRequest_DecodingParametersEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> decodingParameters_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetDecodingParameters() {
      if (decodingParameters_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            DecodingParametersDefaultEntryHolder.defaultEntry);
     }
      return decodingParameters_;
    }
    /**
     * <code>map&lt;string, string&gt; decoding_parameters = 2;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getDecodingParameters() {
      return internalGetDecodingParameters().getMap();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < encBlocks_.size(); i++) {
        output.writeBytes(1, encBlocks_.get(i));
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetDecodingParameters().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        decodingParameters = DecodingParametersDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(2, decodingParameters);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < encBlocks_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(encBlocks_.get(i));
        }
        size += dataSize;
        size += 1 * getEncBlocksList().size();
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetDecodingParameters().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        decodingParameters = DecodingParametersDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, decodingParameters);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static Playcloud.DecodeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Playcloud.DecodeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Playcloud.DecodeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Playcloud.DecodeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Playcloud.DecodeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Playcloud.DecodeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Playcloud.DecodeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Playcloud.DecodeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Playcloud.DecodeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Playcloud.DecodeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Playcloud.DecodeRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DecodeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DecodeRequest)
        Playcloud.DecodeRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Playcloud.internal_static_DecodeRequest_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetDecodingParameters();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableDecodingParameters();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Playcloud.internal_static_DecodeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Playcloud.DecodeRequest.class, Playcloud.DecodeRequest.Builder.class);
      }

      // Construct using ch.unine.iiun.safecloud.Playcloud.DecodeRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        encBlocks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableDecodingParameters().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Playcloud.internal_static_DecodeRequest_descriptor;
      }

      public Playcloud.DecodeRequest getDefaultInstanceForType() {
        return Playcloud.DecodeRequest.getDefaultInstance();
      }

      public Playcloud.DecodeRequest build() {
        Playcloud.DecodeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Playcloud.DecodeRequest buildPartial() {
        Playcloud.DecodeRequest result = new Playcloud.DecodeRequest(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          encBlocks_ = java.util.Collections.unmodifiableList(encBlocks_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.encBlocks_ = encBlocks_;
        result.decodingParameters_ = internalGetDecodingParameters();
        result.decodingParameters_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Playcloud.DecodeRequest) {
          return mergeFrom((Playcloud.DecodeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Playcloud.DecodeRequest other) {
        if (other == Playcloud.DecodeRequest.getDefaultInstance()) return this;
        if (!other.encBlocks_.isEmpty()) {
          if (encBlocks_.isEmpty()) {
            encBlocks_ = other.encBlocks_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEncBlocksIsMutable();
            encBlocks_.addAll(other.encBlocks_);
          }
          onChanged();
        }
        internalGetMutableDecodingParameters().mergeFrom(
            other.internalGetDecodingParameters());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Playcloud.DecodeRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Playcloud.DecodeRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.protobuf.ByteString> encBlocks_ = java.util.Collections.emptyList();
      private void ensureEncBlocksIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          encBlocks_ = new java.util.ArrayList<com.google.protobuf.ByteString>(encBlocks_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes enc_blocks = 1;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getEncBlocksList() {
        return java.util.Collections.unmodifiableList(encBlocks_);
      }
      /**
       * <code>repeated bytes enc_blocks = 1;</code>
       */
      public int getEncBlocksCount() {
        return encBlocks_.size();
      }
      /**
       * <code>repeated bytes enc_blocks = 1;</code>
       */
      public com.google.protobuf.ByteString getEncBlocks(int index) {
        return encBlocks_.get(index);
      }
      /**
       * <code>repeated bytes enc_blocks = 1;</code>
       */
      public Builder setEncBlocks(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEncBlocksIsMutable();
        encBlocks_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes enc_blocks = 1;</code>
       */
      public Builder addEncBlocks(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEncBlocksIsMutable();
        encBlocks_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes enc_blocks = 1;</code>
       */
      public Builder addAllEncBlocks(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureEncBlocksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, encBlocks_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes enc_blocks = 1;</code>
       */
      public Builder clearEncBlocks() {
        encBlocks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> decodingParameters_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetDecodingParameters() {
        if (decodingParameters_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              DecodingParametersDefaultEntryHolder.defaultEntry);
       }
        return decodingParameters_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableDecodingParameters() {
        onChanged();;
        if (decodingParameters_ == null) {
          decodingParameters_ = com.google.protobuf.MapField.newMapField(
              DecodingParametersDefaultEntryHolder.defaultEntry);
        }
        if (!decodingParameters_.isMutable()) {
          decodingParameters_ = decodingParameters_.copy();
        }
        return decodingParameters_;
      }
      /**
       * <code>map&lt;string, string&gt; decoding_parameters = 2;</code>
       */
      public java.util.Map<java.lang.String, java.lang.String> getDecodingParameters() {
        return internalGetDecodingParameters().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; decoding_parameters = 2;</code>
       */
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableDecodingParameters() {
        return internalGetMutableDecodingParameters().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; decoding_parameters = 2;</code>
       */
      public Builder putAllDecodingParameters(
          java.util.Map<java.lang.String, java.lang.String> values) {
        getMutableDecodingParameters().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:DecodeRequest)
    }

    // @@protoc_insertion_point(class_scope:DecodeRequest)
    private static final Playcloud.DecodeRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Playcloud.DecodeRequest();
    }

    public static Playcloud.DecodeRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DecodeRequest>
        PARSER = new com.google.protobuf.AbstractParser<DecodeRequest>() {
      public DecodeRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new DecodeRequest(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<DecodeRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DecodeRequest> getParserForType() {
      return PARSER;
    }

    public Playcloud.DecodeRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DecodeReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DecodeReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes dec_block = 1;</code>
     */
    com.google.protobuf.ByteString getDecBlock();
  }
  /**
   * Protobuf type {@code DecodeReply}
   */
  public  static final class DecodeReply extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DecodeReply)
      DecodeReplyOrBuilder {
    // Use DecodeReply.newBuilder() to construct.
    private DecodeReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DecodeReply() {
      decBlock_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private DecodeReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              decBlock_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Playcloud.internal_static_DecodeReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Playcloud.internal_static_DecodeReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Playcloud.DecodeReply.class, Playcloud.DecodeReply.Builder.class);
    }

    public static final int DEC_BLOCK_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString decBlock_;
    /**
     * <code>optional bytes dec_block = 1;</code>
     */
    public com.google.protobuf.ByteString getDecBlock() {
      return decBlock_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!decBlock_.isEmpty()) {
        output.writeBytes(1, decBlock_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!decBlock_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, decBlock_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static Playcloud.DecodeReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Playcloud.DecodeReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Playcloud.DecodeReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Playcloud.DecodeReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Playcloud.DecodeReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Playcloud.DecodeReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Playcloud.DecodeReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Playcloud.DecodeReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Playcloud.DecodeReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Playcloud.DecodeReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Playcloud.DecodeReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DecodeReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DecodeReply)
        Playcloud.DecodeReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Playcloud.internal_static_DecodeReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Playcloud.internal_static_DecodeReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Playcloud.DecodeReply.class, Playcloud.DecodeReply.Builder.class);
      }

      // Construct using ch.unine.iiun.safecloud.Playcloud.DecodeReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        decBlock_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Playcloud.internal_static_DecodeReply_descriptor;
      }

      public Playcloud.DecodeReply getDefaultInstanceForType() {
        return Playcloud.DecodeReply.getDefaultInstance();
      }

      public Playcloud.DecodeReply build() {
        Playcloud.DecodeReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Playcloud.DecodeReply buildPartial() {
        Playcloud.DecodeReply result = new Playcloud.DecodeReply(this);
        result.decBlock_ = decBlock_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Playcloud.DecodeReply) {
          return mergeFrom((Playcloud.DecodeReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Playcloud.DecodeReply other) {
        if (other == Playcloud.DecodeReply.getDefaultInstance()) return this;
        if (other.getDecBlock() != com.google.protobuf.ByteString.EMPTY) {
          setDecBlock(other.getDecBlock());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Playcloud.DecodeReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Playcloud.DecodeReply) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString decBlock_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes dec_block = 1;</code>
       */
      public com.google.protobuf.ByteString getDecBlock() {
        return decBlock_;
      }
      /**
       * <code>optional bytes dec_block = 1;</code>
       */
      public Builder setDecBlock(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        decBlock_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes dec_block = 1;</code>
       */
      public Builder clearDecBlock() {
        
        decBlock_ = getDefaultInstance().getDecBlock();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:DecodeReply)
    }

    // @@protoc_insertion_point(class_scope:DecodeReply)
    private static final Playcloud.DecodeReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Playcloud.DecodeReply();
    }

    public static Playcloud.DecodeReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DecodeReply>
        PARSER = new com.google.protobuf.AbstractParser<DecodeReply>() {
      public DecodeReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new DecodeReply(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<DecodeReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DecodeReply> getParserForType() {
      return PARSER;
    }

    public Playcloud.DecodeReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_EncodeRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EncodeRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_EncodeRequest_EncodingParametersEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EncodeRequest_EncodingParametersEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_EncodeReply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EncodeReply_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_DecodeRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DecodeRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_DecodeRequest_DecodingParametersEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DecodeRequest_DecodingParametersEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_DecodeReply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DecodeReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017playcloud.proto\"\240\001\n\rEncodeRequest\022\017\n\007p" +
      "ayload\030\001 \001(\014\022C\n\023encoding_parameters\030\002 \003(" +
      "\0132&.EncodeRequest.EncodingParametersEntr" +
      "y\0329\n\027EncodingParametersEntry\022\013\n\003key\030\001 \001(" +
      "\t\022\r\n\005value\030\002 \001(\t:\0028\001\"!\n\013EncodeReply\022\022\n\ne" +
      "nc_blocks\030\001 \001(\014\"\243\001\n\rDecodeRequest\022\022\n\nenc" +
      "_blocks\030\001 \003(\014\022C\n\023decoding_parameters\030\002 \003" +
      "(\0132&.DecodeRequest.DecodingParametersEnt" +
      "ry\0329\n\027DecodingParametersEntry\022\013\n\003key\030\001 \001" +
      "(\t\022\r\n\005value\030\002 \001(\t:\0028\001\" \n\013DecodeReply\022\021\n\t",
      "dec_block\030\001 \001(\0142d\n\016EncoderDecoder\022(\n\006Enc" +
      "ode\022\016.EncodeRequest\032\014.EncodeReply\"\000\022(\n\006D" +
      "ecode\022\016.DecodeRequest\032\014.DecodeReply\"\000b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_EncodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EncodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_EncodeRequest_descriptor,
        new java.lang.String[] { "Payload", "EncodingParameters", });
    internal_static_EncodeRequest_EncodingParametersEntry_descriptor =
      internal_static_EncodeRequest_descriptor.getNestedTypes().get(0);
    internal_static_EncodeRequest_EncodingParametersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_EncodeRequest_EncodingParametersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_EncodeReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EncodeReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_EncodeReply_descriptor,
        new java.lang.String[] { "EncBlocks", });
    internal_static_DecodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DecodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DecodeRequest_descriptor,
        new java.lang.String[] { "EncBlocks", "DecodingParameters", });
    internal_static_DecodeRequest_DecodingParametersEntry_descriptor =
      internal_static_DecodeRequest_descriptor.getNestedTypes().get(0);
    internal_static_DecodeRequest_DecodingParametersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DecodeRequest_DecodingParametersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_DecodeReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_DecodeReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DecodeReply_descriptor,
        new java.lang.String[] { "DecBlock", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
